export const initial = {
  calculed: false,
  route: null,
  addAdress: true,
  deliveryRetorn: false,
  travelMode: 'DRIVING',
  optimizeWaypoints: true,
  vehicleType: 0,
  serviceType: 0,
  dataToDelivery: {
    totaToPay: 0,
    timeDelivery: 0,
    distanceTotal: 0,
    deliveriesTotal: 0,
  },
  address: '',
  delivery: {
    id: Math.random(),
    street: '',
    number: 0,
    complement: '',
    neighborhood: '',
    city: '',
    state: '',
    longitude: 0,
    latitude: 0,
    obs: '',
    address: '',
    payment: 0,
  },
  deliveries: [
    {
      id: Math.random(),
      street: 'Rua Alberto Gadelha,80, Mâncio Lima - Acre',
      number: '80',
      complement: '',
      neighborhood: 'centro',
      city: 'Mâncio Lima',
      state: 'Acre',
      longitude: -72.906094,
      latitude: -7.61368,
      obs: '',
      address: 'Rua Alberto Gadelha,80, Mâncio Lima - Acre',
    },
  ],
};
