import { ResponseDataLogin } from '../types/provider';

const loginDataObject: ResponseDataLogin = {
  data: {
    data: {
      token: '123',
      banks: [{ id: 123, name: 'testBank' }],
      payBlock: false,
      payments: [
        {
          id: 123,
          type: { id: 123, name: 'test' },
          flag: { id: 123, name: 'test', picture: '123' },
        },
      ],
      providercategories: [
        {
          banner: 'test',
          catPriority: 123,
          icon: 'test',
          id: 123,
          name: 'test',
          priority: 123,
        },
      ],
      user: {
        cities: [
          {
            code: 123,
            franchise: [
              {
                addkm: 'test',
                addpoint: 'test',
                addpointmult: 'test',
                alias: 'test',
                basekm: 'test',
                basekmmulti: 'test',
                blackholiday: true,
                city: 'test',
                currency: 'test',
                deliverytax: 'test',
                document: 'test',
                endereco: 123,
                fkcity: 123,
                franchiseAdress: {
                  address: 'test',
                  city: 123,
                  complement: 'test',
                  country: 123,
                  id: 123,
                  latitude: 123,
                  longitude: 123,
                  name: 'test',
                  neighborhood: 'test',
                  number: 'test',
                  postal: 'test',
                  reference: 'test',
                  state: 123,
                  status: 123,
                  type: 0,
                  user: 123,
                },
                franchiseParameters: {
                  canProviderSetOwnShopper: true,
                  iframe: 'test',
                },
                franchiseUser: {},
              },
            ],
            id: 123,
            name: 'test',
            state: 123,
            stateob: { id: 123, name: 'test', state: 123 },
            status: true,
          },
        ],
        data: {
          FranchiseProviderSetOwnShopper: true,
          birthday: 'test',
          canProviderSetOwnShopper: true,
          createdAt: 'test',
          email: 'test@example.com',
          franchise: {
            addkm: 'test',
            addpoint: 'test',
            addpointmult: 'test',
            alias: 'test',
            basekm: 'test',
            basekmmulti: 'test',
            blockholiday: true,
            city: 'test',
            currency: 123,
            deliverytax: 'test',
            document: 'test',
            endereco: 123,
            fkcity: 123,
            franchiseAdress: {
              address: 'test',
              city: 123,
              complement: null,
              country: 123,
              id: 123,
              latitude: 123,
              longitude: 123,
              name: 'test',
              neighborhood: 'test',
              number: 'test',
              postal: 'test',
              reference: 'test',
              state: 123,
              status: 123,
              type: 123,
              user: 123,
            },
            franchiseParameters: {
              canProviderSetOwnShopper: true,
              iframe: 'test',
            },
            franchiseUser: {
              account: [],
              addresses: [
                {
                  address: 'test',
                  city: 123,
                  complement: 'test',
                  country: 123,
                  id: 123,
                  latitude: 123,
                  longitude: 123,
                  name: 'test',
                  neighborhood: 'test',
                  number: 'test',
                  postal: 'test',
                  reference: 'test',
                  state: 123,
                  status: 123,
                  type: 123,
                  user: 123,
                },
              ],
              birthday: 'test',
              createdAt: 'test',
              email: 'test',
              gender: 123,
              id: 123,
              name: 'test',
              password: 'test',
              phone: 'test',
              picture: 'test',
              status: 123,
              userType: 123,
            },
          },
          id: 123,
          logisticType: 'test',
          maxdist: 'test',
          maxfare: 'test',
          mktplacekm: 'test',
          name: 'test',
          online: true,
          operationType: 123,
          referee: true,
          returntax: 'test',
          seller: 'test',
          shoppertime: 'test',
          status: 123,
          tax: 'test',
          timeZone: 'test',
          user: 123,
          working: true,
          zpk: 'test',
        },
        franchises: [{ id: 123, name: 'test' }],
        states: [{ id: 123, name: 'teste', state: 123 }],
      },
    },
    error: undefined,
  },
};

export default loginDataObject.data;
